name: Build GUI

on: 
  push:
    paths:
      - gui/**
      - package*.json
  pull_request:
    paths:
      - gui/**
      - package*.json

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]

    env:
      # Don't mark warnings as errors
      CI: false

    steps:
      - uses: actions/checkout@v3

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn tauri build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: SlimeVR-GUI
          # A file, directory or wildcard pattern that describes what to upload
          path: gui/target/release/slimevr-ui.exe
